lookahead_distance : 0.24 #one bakma mesafesi
speed : 0.18 #maksimum hiz
expansion_size : 5 #duvar genisletme katsayisi
target_error : 0.15 #hedefe olan hata payi
robot_r : 0.4 #lokal guvenlik icin robot mesafesi

# lookahead_distance: 0.24 - Lookahead distance (the distance the robot looks ahead on its path)
# speed: 0.18 - Maximum speed (the maximum speed the robot can move)
# expansion_size: 3 - Wall expansion factor (the factor by which walls/obstacles are expanded for planning)
# target_error: 0.15 - Target error margin (the acceptable error margin when reaching the target)
# robot_r: 0.2 - Robot distance for local safety (the distance for local safety around the robot)